### ISSUE TITLE
Error: connect  EHOSTUNREACH

### ISSUE THREAD

**Issue by KrX3D** [iobroker-community-adapters/ioBroker.openhab#34]
Hello,

im getting this error:

openhab.0 | 2020-11-07 22:27:43.236 | error | (29781)  Cannot get answer from  "http://192.168.0.101:8080/rest/items?recursive=false": Error: connect  EHOSTUNREACH 192.168.0.101:8080
-- | -- | -- | --

but going to "http://192.168.0.101:8080/rest/items?recursive=false" via browser i get a list of my items so what is wrong?

![grafik](https://user-images.githubusercontent.com/18599852/98451796-77225500-2149-11eb-81d3-4ee9ccad8ab6.png)

**Comment by Apollon77** [comment]
did you teally tried it from the same host as iobroker runs on? Maybe try via "wget" or "curl" from that host

**Comment by KrX3D** [comment]
hi,

my setup:

i have a NAS with Unraid as OS, on it i run different docker images.

iobroker docker image has the ip 192.168.0.113 Port 8081
openhab docker image has the ip 192.168.0.101 Port 8080

when i start the openhab adapter i get the error:


openhab.0 | 2020-11-08 09:55:36.069 | error | (31404)  Cannot get answer from  "http://192.168.0.101:8080/rest/items?recursive=false": Error: connect  EHOSTUNREACH 192.168.0.101:8080
-- | -- | -- | --


but when i access the link from this error "http://192.168.0.101:8080/rest/items?recursive=false" via my notebook browser i see this:

![grafik](https://user-images.githubusercontent.com/18599852/98460931-ccda1a00-21a8-11eb-815b-f6ebe279afac.png)

**Comment by Apollon77** [comment]
Network is different ... sorry but here you need to see why the openhab docker container can not reached from the second docker container ... this has nothing to d with the adapter. I think the Forum or docker support forums can help more.

**Comment by KrX3D** [comment]
thanks for the hint, i changed the ip of the openhab docker image also to 192.168.0.113 and now it works
