### ISSUE TITLE
unknown type: image

### ISSUE THREAD

**Issue by turbocyx** [iobroker-community-adapters/ioBroker.openhab#60]
get the following in iobroker:

openhab.0 | 2022-05-26 10:52:32.989 | warn | oh2iob - Unknown type: image
 
fixable?

**Comment by Apollon77** [comment]
Hi,

Anything is fixable!

Is it fixable with these many information you provided... most likely not :-)

Please enable the debug loglevel for the openhab instance on "instance" tab (with active export mode) and post the full log from adapterstart. Please get log from logfile on disk and not from admin ... /opt/iobroekr/log/...)

There is an object from OpenHab with type "image" which is not supported currently to map to iobroker ... so we need to investigate it in depth

**Comment by turbocyx** [comment]
Sorry for late answer - kicke openhab out of my iobroker .. so no logs from me sorry ...
